### ISSUE TITLE
Kubernetes StatefulSet apps/v1beta1 no longer available since K8S 1.16

### ISSUE THREAD

**Issue by griseau** [vespa-engine/vespa#19798]
In the [vespa quick start example](https://docs.vespa.ai/documentation/vespa-quick-start-kubernetes.html), the version of the StatefulSet is apps/v1beta1, however this version has been deprecated and is now removed since [kubernetes 1.16](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). 
We just need to change the apiVersion to `apps/v1` and add a selector in the spec that match the label. 
This will give the following : 
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  replicas: 1
  serviceName: vespa
  selector:
    matchLabels:
      app: vespa # <- this value needs to be added and must match template.metadata.labels
  template:
    metadata:
      labels:
        app: vespa
    spec:
      containers:
      - name: vespa
        image: vespaengine/vespa
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ApplicationStatus
            port: 19071
            scheme: HTTP
        volumeMounts:
        - name: vespa-sample-apps
          mountPath: /vespa-sample-apps
      volumes:
      - name: vespa-sample-apps
        hostPath:
          path: PATH_TO_CLONED/sample-apps
```

I guess you have other kubernetes files that might be impacted. 
Edit: I checked, basic-search-on-gke is already using apps/v1
