### ISSUE TITLE
kubernetes ingress and needed port to use vespa

### ISSUE THREAD

**Issue by lundin** [vespa-engine/vespa#4511]
Hi!
I looked into this issue:
https://github.com/vespa-engine/vespa/issues/3640
But could not make every part of vespa work to for example deploy apps and start using it.

Did you ever managed to created a ingress (i am on GKE) and manage it to work with vespa tools and endpoints ?
I can reach the config endpoint mydomain.com/ApplicationStatus due to the mapping in the ingress pointing to the config port (nodeport service).
But now i am trying to use the deploy API with the endpoints in:
http://docs.vespa.ai/documentation/cloudconfig/deploy-rest-api-v2.html#use-cases

It seems that i need to have multiple (at least two ports 80(80) and 19071 on the same domain open) and ingress does not support that without specify different paths
https://github.com/kubernetes/ingress-nginx/issues/1655

POSTING to 
http://mydomain.com/application/v2/tenant/mytenant/session
just return 404 -default backend

and specify
http://mydomain.com:19701/application/v2/tenant/mytenant/session
hangs.

Anyone has a suggestion how i can create the ingress exposing needed ports ? Mabey one can create multiple services maped to different hosts (vespaapi.mydomain.com using 19071 and mydomain.com using 80)

Service:
```
apiVersion: v1
kind: Service
metadata:
  name: vespa
  labels:
    app: vespa
spec:
  selector:
    app: vespa
  type: NodePort
  ports:
  - name: sample-app
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: config
    port: 19071
    targetPort: 19071
    protocol: TCP
```

Ingress:

```
- host: mydomain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: vespa
          servicePort: 80
      - path: /ApplicationStatus
        backend:
          serviceName: vespa
          servicePort: 19071
```
